version: '3.8'
 
services:
  nextcloud_db:
    image: mariadb
    container_name: nextcloud_db
    restart: always
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    volumes:
    - ./db:/var/lib/mysql
    environment:
    - MYSQL_ROOT_PASSWORD=$NEXTCLOUD_MYSQL_ROOT_PASSWORD
    - MYSQL_DATABASE=$NEXTCLOUD_MYSQL_DATABASE
    - MYSQL_USER=$NEXTCLOUD_MYSQL_USER
    - MYSQL_PASSWORD=$NEXTCLOUD_MYSQL_PASSWORD
 
  nextcloud_app:
    image: nextcloud
    restart: always
    ports:
     - $NEXTCLOUD_PORT:80
    links:
     - nextcloud_db
    volumes:
     - ./data:/var/www/html
    environment:
    - MYSQL_HOST=nextcloud_db
    - MYSQL_DATABASE=$NEXTCLOUD_MYSQL_DATABASE
    - MYSQL_USER=$NEXTCLOUD_MYSQL_USER
    - MYSQL_PASSWORD=$NEXTCLOUD_MYSQL_PASSWORD
 